In [43]:
import cv2  #openCV的读取格式默认是BGR而不是RGB
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

img=cv2.imread('Lena.jpg')

In [44]:
img

array([[[123, 137, 225],
        [123, 137, 225],
        [120, 137, 224],
        ...,
        [131, 140, 238],
        [131, 145, 241],
        [103, 120, 213]],

       [[123, 137, 225],
        [121, 138, 225],
        [121, 138, 225],
        ...,
        [140, 144, 239],
        [136, 144, 237],
        [102, 113, 203]],

       [[120, 137, 224],
        [120, 137, 224],
        [120, 136, 225],
        ...,
        [133, 128, 219],
        [125, 122, 208],
        [ 94,  94, 178]],

       ...,

       [[ 59,  28,  91],
        [ 61,  27,  92],
        [ 63,  26,  94],
        ...,
        [ 75,  56, 143],
        [ 81,  62, 155],
        [ 82,  64, 158]],

       [[ 55,  26,  89],
        [ 58,  26,  91],
        [ 62,  25,  93],
        ...,
        [ 82,  64, 153],
        [ 85,  69, 163],
        [ 84,  70, 166]],

       [[ 54,  25,  88],
        [ 60,  28,  93],
        [ 64,  27,  95],
        ...,
        [ 90,  74, 162],
        [ 90,  76, 172],
        [ 88,  75, 173]]

In [45]:
cv2.imshow('pic',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
img

array([[[123, 137, 225],
        [123, 137, 225],
        [120, 137, 224],
        ...,
        [131, 140, 238],
        [131, 145, 241],
        [103, 120, 213]],

       [[123, 137, 225],
        [121, 138, 225],
        [121, 138, 225],
        ...,
        [140, 144, 239],
        [136, 144, 237],
        [102, 113, 203]],

       [[120, 137, 224],
        [120, 137, 224],
        [120, 136, 225],
        ...,
        [133, 128, 219],
        [125, 122, 208],
        [ 94,  94, 178]],

       ...,

       [[ 59,  28,  91],
        [ 61,  27,  92],
        [ 63,  26,  94],
        ...,
        [ 75,  56, 143],
        [ 81,  62, 155],
        [ 82,  64, 158]],

       [[ 55,  26,  89],
        [ 58,  26,  91],
        [ 62,  25,  93],
        ...,
        [ 82,  64, 153],
        [ 85,  69, 163],
        [ 84,  70, 166]],

       [[ 54,  25,  88],
        [ 60,  28,  93],
        [ 64,  27,  95],
        ...,
        [ 90,  74, 162],
        [ 90,  76, 172],
        [ 88,  75, 173]]

In [47]:
img=cv2.imread('Lena.jpg',cv2.IMREAD_GRAYSCALE)
img

array([[162, 162, 161, ..., 168, 172, 146],
       [162, 162, 162, ..., 172, 171, 139],
       [161, 161, 161, ..., 156, 148, 119],
       ...,
       [ 50,  50,  51, ...,  84,  92,  94],
       [ 48,  49,  50, ...,  93,  99, 100],
       [ 47,  51,  52, ..., 102, 106, 106]], dtype=uint8)

In [58]:
binary=cv2.im2bw(img,0.2)
imshow(binary)

AttributeError: module 'cv2' has no attribute 'im2bw'

In [50]:
cv2.imwrite('gray.jpg',img)

True

In [51]:
top2_line=img[:2,:]
top2_line

array([[162, 162, 161, 161, 161, 161, 160, 159, 158, 158, 158, 156, 155,
        154, 155, 156, 156, 158, 161, 164, 167, 170, 173, 175, 172, 171,
        168, 161, 153, 145, 129, 110,  97,  92,  94, 101, 102, 104, 106,
        105, 109, 107, 106, 108, 109, 109, 109, 110, 109, 108, 107, 106,
        109, 114, 118, 119, 118, 123, 123, 124, 127, 126, 126, 129, 133,
        130, 129, 130, 133, 134, 132, 129, 129, 129, 129, 129, 130, 132,
        134, 136, 132, 134, 135, 134, 133, 133, 133, 132, 136, 134, 133,
        134, 135, 136, 134, 132, 135, 135, 136, 137, 137, 136, 135, 134,
        136, 135, 133, 131, 130, 130, 131, 132, 131, 133, 134, 133, 131,
        132, 132, 131, 137, 135, 135, 136, 135, 132, 132, 134, 140, 135,
        130, 130, 133, 134, 133, 130, 126, 130, 130, 133, 127, 130, 128,
        132, 129, 130, 129, 127, 128, 129, 130, 129, 122, 122, 120, 118,
        117, 115, 109, 103, 110, 117, 127, 136, 143, 149, 154, 157, 159,
        162, 160, 153, 150, 152, 153, 152, 152, 154

In [52]:
import numpy
average=numpy.mean(top2_line)
median=numpy.median(top2_line)
ret, thresh1=cv2.threshold(img,average,255,cv2.THRESH_BINARY)
ret, thresh2=cv2.threshold(img,median,255,cv2.THRESH_BINARY)
cv2.imshow('pic1',thresh2)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('thresh2.jpg',thresh2)

True

In [53]:
average=numpy.mean(img)
median=numpy.median(img)
ret, thresh3=cv2.threshold(img,average,255,cv2.THRESH_BINARY)
ret, thresh4=cv2.threshold(img,median,255,cv2.THRESH_BINARY)
cv2.imwrite('thresh3.jpg',thresh3)
cv2.imwrite('thresh4.jpg',thresh4)

True

In [54]:
h,w=img.shape[:2]
h

256

In [55]:
firstHalf=img[0:127,:]

In [56]:
ret, half1=cv2.threshold(firstHalf,average,255,cv2.THRESH_BINARY)
result=img.copy()
result[:127,:]=half1
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('result.jpg',result)

True

In [1]:
import cv2
cv2.__version__

'4.8.1'